version: 2.1

workflows:
  SIG:
    jobs:
      - blackduck:
          context:
            - Black Duck
      - coverity:
          context:
            - Coverity
      - polaris:
          context:
            - Polaris

jobs:
  blackduck:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - run:
          name: Black Duck
          command: |
            curl -fLOsS https://detect.synopsys.com/detect7.sh
            bash detect7.sh --detect.project.name=chuckaude-$CIRCLE_PROJECT_REPONAME --detect.project.version.name=$CIRCLE_BRANCH

  coverity:
    docker:
      - image: circleci/openjdk:11-jdk
    environment:
      BLDCMD: 'mvn -B package -DskipTests'
    steps:
      - checkout
      - run:
          name: Coverity
          command: |
            rm -rf /tmp/ctc && mkdir /tmp/ctc
            curl -fLsS $COV_URL/api/v2/scans/downloads/cov_thin_client-linux64-2022.3.1.tar.gz | tar -C /tmp/ctc -xzf -
            COVERITY_CLI_CLOUD_ANALYSIS_ASYNC=false /tmp/ctc/bin/coverity scan -o analyze.location=connect \
              -o commit.connect.url=$COV_URL -o commit.connect.stream=$CIRCLE_PROJECT_REPONAME-$CIRCLE_BRANCH -- $BLDCMD

  polaris:
    docker:
      - image: circleci/openjdk:11-jdk
    environment:
      BLDCMD: 'mvn -B package -DskipTests'
    steps:
      - checkout
      - run:
          name: Polaris
          command: |
            curl -fLOsS $POLARIS_SERVER_URL/api/tools/polaris_cli-linux64.zip
            unzip -d /tmp -jo polaris_cli-linux64.zip
            /tmp/polaris --co project.name=chuckaude-$CIRCLE_PROJECT_REPONAME analyze -w -- $BLDCMD
