# example pipeline for Coverity scans using the Synopsys Security Scan extension for ADO
# https://marketplace.visualstudio.com/items?itemName=synopsys-security-scan.synopsys-security-scan
trigger:
- main
- develop
pool:
  vmImage: ubuntu-latest
variables:
  - group: poc357.coverity.synopsys.com
steps:
- task: JavaToolInstaller@0
  displayName: 'Use Java 17'
  inputs:
    versionSpec: 17
    jdkArchitectureOption: x64
    jdkSourceOption: PreInstalled
- task: Maven@4
  displayName: 'Maven Build'
  inputs:
    options: '-B -DskipTests'
- task: SynopsysSecurityScan@1
  displayName: 'Coverity Full Scan'
  condition: not(eq(variables['Build.Reason'], 'PullRequest'))
  inputs:
    coverity_url: $(COVERITY_URL)
    coverity_user: $(COV_USER)
    coverity_passphrase: $(COVERITY_PASSPHRASE)
    coverity_project_name: $(Build.Repository.Name)
    coverity_stream_name: $(Build.Repository.Name)-$(Build.SourceBranchName)
    coverity_policy_view: 'Outstanding Issues'
    # coverity_local: true
    # include_diagnostics: true
- task: SynopsysSecurityScan@1
  displayName: 'Coverity PR Scan'
  condition: eq(variables['Build.Reason'], 'PullRequest')
  inputs:
    coverity_url: $(COVERITY_URL)
    coverity_user: $(COV_USER)
    coverity_passphrase: $(COVERITY_PASSPHRASE)
    coverity_project_name: $(Build.Repository.Name)
    coverity_stream_name: $(Build.Repository.Name)-$(System.PullRequest.targetBranchName)
    coverity_prcomment_enabled: true
    azure_token: $(System.AccessToken)
    # coverity_local: true
    # include_diagnostics: true
- task: ArchiveFiles@2
  displayName: 'Copy Log Files'
  condition: succeededOrFailed()
  enabled: false
  inputs:
    rootFolderOrFile: .bridge
    includeRootFolder: false
    archiveFile: '$(Build.ArtifactStagingDirectory)/bridge-logs.zip'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Log Files'
  condition: succeededOrFailed()
  enabled: false
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'logs'
