# example pipeline for Polaris scans using the Synopsys Security Scan extension for ADO
# https://marketplace.visualstudio.com/items?itemName=synopsys-security-scan.synopsys-security-scan
trigger:
- main
- develop
pool:
  vmImage: ubuntu-latest
variables:
  - group: poc.polaris.synopsys.com
steps:
- task: JavaToolInstaller@0
  displayName: 'Use Java 17'
  inputs:
    versionSpec: 17
    jdkArchitectureOption: x64
    jdkSourceOption: PreInstalled
- task: Maven@4
  displayName: 'Maven Build'
  inputs:
    options: '-B -DskipTests'
- task: SynopsysSecurityScan@1
  displayName: 'Polaris Full Scan'
  condition: not(eq(variables['Build.Reason'], 'PullRequest'))
  inputs:
    polaris_server_url: $(POLARIS_SERVERURL)
    polaris_access_token: $(POLARIS_ACCESSTOKEN)
    polaris_assessment_types: 'SAST,SCA'
    polaris_application_name: chuckaude-$(Build.Repository.Name)
    polaris_project_name: $(Build.Repository.Name)
    polaris_branch_name: $(Build.SourceBranchName)
    polaris_reports_sarif_create: true
    # include_diagnostics: true
- task: SynopsysSecurityScan@1
  displayName: 'Polaris PR Scan'
  condition: eq(variables['Build.Reason'], 'PullRequest')
  inputs:
    polaris_server_url: $(POLARIS_SERVERURL)
    polaris_access_token: $(POLARIS_ACCESSTOKEN)
    polaris_assessment_types: 'SAST,SCA'
    polaris_application_name: chuckaude-$(Build.Repository.Name)
    polaris_project_name: $(Build.Repository.Name)
    polaris_branch_name: $(Build.SourceBranchName)
    polaris_branch_parent_name: $(System.PullRequest.targetBranchName)
    polaris_prcomment_enabled: true
    azure_token: $(System.AccessToken)
    # include_diagnostics: true
- task: ArchiveFiles@2
  displayName: 'Copy Log Files'
  condition: succeededOrFailed()
  enabled: false
  inputs:
    rootFolderOrFile: .bridge
    includeRootFolder: false
    archiveFile: '$(Build.ArtifactStagingDirectory)/bridge-logs.zip'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Log Files'
  condition: succeededOrFailed()
  enabled: false
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'logs'
